"""Create Camera table

Revision ID: 5a3fabe71f13
Revises: 984b667ef077
Create Date: 2025-06-05 14:47:58.607286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a3fabe71f13'
down_revision: Union[str, None] = '984b667ef077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False, comment='Номер камеры'),
    sa.Column('camera_class_cd', sa.Integer(), nullable=False, comment='Идентификатор класса камеры'),
    sa.Column('camera_class', sa.String(), nullable=False, comment='Класс камеры'),
    sa.Column('model', sa.String(), nullable=False, comment='Модель'),
    sa.Column('camera_name', sa.String(), nullable=False, comment='Название камеры'),
    sa.Column('camera_place', sa.String(), nullable=False, comment='Адрес'),
    sa.Column('camera_place_cd', sa.Integer(), nullable=False, comment='Идентификатор адреса'),
    sa.Column('serial_number', sa.String(), nullable=False, comment='Серийный номер'),
    sa.Column('camera_type_cd', sa.Integer(), nullable=False, comment='Идентификатор типа камеры'),
    sa.Column('camera_type', sa.String(), nullable=False, comment='Тип камеры'),
    sa.Column('camera_latitude', sa.Float(), nullable=False, comment='Широта'),
    sa.Column('camera_longitude', sa.Float(), nullable=False, comment='Долгота'),
    sa.Column('archive', sa.Boolean(), nullable=False, comment='Признак архивной записи'),
    sa.Column('azimuth', sa.Integer(), nullable=False, comment='Азимут'),
    sa.Column('process_dttm', sa.DateTime(), nullable=False, comment='Дата и время добавления записи'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###
