"""Create Video table

Revision ID: 94618c659f63
Revises: 3a8499ebc4e4
Create Date: 2025-06-06 16:29:35.130061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94618c659f63'
down_revision: Union[str, None] = '3a8499ebc4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('video_resolution', sa.String(), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('time_of_day', sa.Enum('MORNING', 'DAY', 'EVENING', 'NIGHT', name='timeofday'), nullable=False),
    sa.Column('tracing', sa.Enum('DONE', 'RUN', 'ERROR', name='tracingstatus'), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('minio_path', sa.String(), nullable=False),
    sa.Column('thumbnail_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
