"""add has_video field to camera

Revision ID: 955c9d76ff16
Revises: 5a3fabe71f13
Create Date: 2025-06-05 17:23:03.433871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '955c9d76ff16'
down_revision: Union[str, None] = '5a3fabe71f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('has_video', sa.Boolean(), nullable=False))
    op.alter_column('cameras', 'process_dttm',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Дата и время добавления записи',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cameras', 'process_dttm',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Дата и время добавления записи',
               existing_nullable=False)
    op.drop_column('cameras', 'has_video')
    # ### end Alembic commands ###
