"""Updating TimeOfDay and TracingStatus

Revision ID: 99e1ade17d5c
Revises: 19eb72a6f15a
Create Date: 2025-06-08 15:39:38.862515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e1ade17d5c'
down_revision: Union[str, None] = '19eb72a6f15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE tracingstatus ADD VALUE IF NOT EXISTS 'Pending';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
