"""Create Video table

Revision ID: bb191da56ee9
Revises: 955c9d76ff16
Create Date: 2025-06-06 15:36:26.412428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb191da56ee9'
down_revision: Union[str, None] = '955c9d76ff16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cameras', 'has_video',
               existing_type=sa.BOOLEAN(),
               comment='Наличие видео у камеры',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cameras', 'has_video',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Наличие видео у камеры',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
